import { officialResults } from "./officialResults.js";

export const industries = [
  "化学药与药用辅料",
  "中药与天然产物",
  "生物制药",
  "食品与农产品",
  "化工与新材料",
  "环境检测",
  "烟草制品",
];

export const detectors = [
  "UNIEX-8700 ELSD 蒸发光散射检测器",
  "UM5800Plus ELSD 蒸发光散射检测器",
  "ELSD 蒸发光散射检测器",
  "URI-3000 RID 示差折光检测器",
  "UV/Vis 紫外可见检测器",
];

export const instruments = [
  "EasySep-3030 液相色谱系统",
  "通微 HPLC 液相色谱系统",
  "AutoCE-3000 全自动毛细管电泳系统",
  "CE-1000 毛细管电泳系统",
];

export const officialDatasetVersion = "official-cases-2026-08-21-v2-complete-results";

const contact = "技术支持｜021-38953588｜info@unimicrotech.com.cn";

function makeConditions(entries) {
  return entries.map(([label, value], index) => ({
    id: `condition-${index + 1}`,
    key: `condition-${index + 1}`,
    label,
    value,
  }));
}

function makeArticle(item, officialResult) {
  const details = officialResult?.details?.length ? `<ul>${officialResult.details.map((detail) => `<li>${detail}</li>`).join("")}</ul>` : "";
  const figures = officialResult?.figures?.map((entry, index) => `<h3>图${index + 1}　${entry.caption}</h3><img src="${entry.src}" alt="${entry.caption}">`).join("") || `<h3>${item.resultCaption}</h3><img src="${item.resultImage}" alt="${item.resultCaption}">`;
  return `<h2>方法与数据</h2><p>${item.method}</p><h2>完整实验结果</h2>${details}${figures}<h2>结果结论</h2><p>${item.result}</p>`;
}

const cases = [
  {
    id: "cce412b6-8ffb-44d4-acf8-7cc94c885c7b",
    title: "UNIEX-8700 ELSD 检测硫酸卡那霉素",
    summary: "按照《中国药典》2025年版要求，在强酸体系下同步考察硫酸卡那霉素含量与卡那霉素B有关物质。",
    industry: "化学药与药用辅料",
    detector: "UNIEX-8700 ELSD 蒸发光散射检测器",
    instrument: "EasySep-3030 液相色谱系统",
    image: "/assets/cases/case-kanamycin-cover.png",
    resultImage: "/assets/cases/case-kanamycin-result.png",
    coverAlt: "硫酸卡那霉素 HPLC-ELSD 应用",
    standardReference: "《中国药典》2025年版：硫酸卡那霉素含量及有关物质检测",
    background: "卡那霉素类物质缺少共轭发色基团，常规UV检测通常需要衍生化。官网案例采用ELSD直接响应弱紫外吸收组分，并考察强酸流动相条件下的系统表现。",
    conditions: [["仪器系统", "EasySep-3030液相色谱系统，配备UNIEX-8700 ELSD"], ["色谱柱", "C18（4.6 mm × 250 mm，5 μm）"], ["流动相", "0.2 mol/L三氟醋酸溶液-甲醇（95:5）"], ["考察组分", "卡那霉素A及有关物质卡那霉素B"]],
    result: "卡那霉素对照品连续进样6针，保留时间RSD为0.05%，峰面积RSD为1.77%；0.10、0.15、0.20 mg/mL三档浓度回归系数r＞0.99，并观察到卡那霉素B响应。",
    method: "采用不依赖发色团的蒸发光散射检测思路，减少柱前或柱后衍生化带来的额外变量，并在同一平台考察重复性、线性和有关物质。",
    resultCaption: "卡那霉素对照品连续6针叠加色谱图",
  },
  {
    id: "c77dc028-78c6-42a0-a8b1-75b0b3a8cfe2",
    title: "HPLC-ELSD 检测罗汉果皂苷V",
    summary: "针对皂苷类成分紫外响应弱的问题，使用EasySep-3030与UM5800Plus ELSD完成罗汉果皂苷V检测。",
    industry: "中药与天然产物",
    detector: "UM5800Plus ELSD 蒸发光散射检测器",
    instrument: "EasySep-3030 液相色谱系统",
    image: "/assets/cases/case-mogroside-cover.png",
    resultImage: "/assets/cases/case-mogroside-result.png",
    coverAlt: "罗汉果皂苷V HPLC-ELSD检测",
    standardReference: "《中国药典》收载品种：罗汉果皂苷V为罗汉果质量控制指标成分",
    background: "罗汉果皂苷V是罗汉果中主要的甜味与指标性成分。皂苷缺少强紫外吸收基团，ELSD可为罗汉果原料及制剂提供不依赖发色团的检测响应。",
    conditions: [["仪器系统", "EasySep-3030液相色谱系统"], ["检测器", "UM5800Plus ELSD"], ["色谱柱", "HOLOWA C18（4.6 mm × 250 mm，5 μm）"], ["重复性", "连续进样6针"]],
    result: "罗汉果皂苷V对照品在8.036 min处获得清晰单峰，拖尾因子1.03；连续6针保留时间RSD为0.16%，峰面积RSD为1.51%，供试品目标峰分离清晰。",
    method: "使用HPLC-ELSD联用技术检测罗汉果皂苷V，对照品、重复性和实际样品均进行验证。",
    resultCaption: "罗汉果皂苷V对照品色谱图",
  },
  {
    id: "ce778be8-168d-4af3-bfc8-ffe659da2ef5",
    title: "CE-SDS法测定司美格鲁肽纯度",
    summary: "使用AutoCE-3000监测司美格鲁肽光照前后的纯度与聚体变化，并验证连续运行重复性。",
    industry: "生物制药",
    detector: "UV/Vis 紫外可见检测器",
    instrument: "AutoCE-3000 全自动毛细管电泳系统",
    image: "/assets/cases/case-semaglutide-cover.png",
    resultImage: "/assets/cases/case-semaglutide-result.png",
    coverAlt: "司美格鲁肽CE-SDS纯度分析",
    standardReference: "",
    background: "司美格鲁肽在光照、热和氧化条件下可能形成聚体或降解片段。CE-SDS能够按分子量差异分离单体、聚体和小分子杂质，是多肽纯度监测的正交分析手段。",
    conditions: [["仪器", "AutoCE-3000全自动毛细管电泳分离系统"], ["石英毛细管", "50 μm i.d.，有效长度26 cm"], ["分离电解质", "CE凝胶（蛋白专用）"], ["样品", "1.5 mg/mL司美格鲁肽"], ["分离条件", "-18 kV"], ["进样", "-5 kV，10 s"], ["检测", "UV/Vis检测器，200 nm"]],
    result: "光照处理后样品纯度由99.95%降至97.85%，聚体杂质由0.05%升至2.15%；连续6针主峰迁移时间RSD为0.3779%，峰面积RSD为1.3344%。",
    method: "对冷藏避光样品和光照处理样品开展非还原CE-SDS对比，并连续运行6针验证系统重复性。",
    resultCaption: "司美格鲁肽CE-SDS纯度分析对比电泳图",
  },
  {
    id: "6ff02df3-b055-4830-9f27-fc856f986b17",
    title: "HPLC-ELSD 检测十八碳二元酸",
    summary: "建立十八碳二元酸（DC18）的HPLC-ELSD检测方法，用于新能源材料关键单体纯度控制。",
    industry: "化工与新材料",
    detector: "UM5800Plus ELSD 蒸发光散射检测器",
    instrument: "EasySep-3030 液相色谱系统",
    image: "/assets/cases/case-dc18-cover.png",
    resultImage: "/assets/cases/case-dc18-cover.png",
    coverAlt: "十八碳二元酸HPLC-ELSD检测",
    standardReference: "",
    background: "十八碳二元酸是生物基聚酰胺1818的关键单体，在短波长区仅有末端吸收，常规UV检测易受到流动相背景和杂质干扰。",
    conditions: [["仪器", "EasySep-3030液相色谱系统，配备UM5800Plus ELSD"], ["色谱柱", "C18（4.6 mm × 250 mm，5 μm）"], ["流动相", "A：0.1% TFA水；B：乙腈"], ["洗脱方式", "梯度洗脱"], ["流速", "1.0 mL/min"], ["柱温", "35 ℃"], ["ELSD参数", "载气2.5 L/min；蒸发温度75 ℃；增益5"]],
    result: "十八碳二元酸在ELSD下保留时间为26.621 min，拖尾因子1.1，峰响应明显高于210 nm紫外检测，可满足纯度检测需求。",
    method: "同一液相条件下分别比较UV与ELSD响应，并用供试品验证方法适用性。",
    resultCaption: "十八碳二元酸HPLC-ELSD应用",
  },
  {
    id: "5ace0b41-7415-4444-8f6b-50216f471fe1",
    title: "URI-3000 RID 检测大豆低聚糖",
    summary: "参考农业农村部公告方法，分离检测大豆低聚糖中的蔗糖、棉子糖和水苏糖。",
    industry: "食品与农产品",
    detector: "URI-3000 RID 示差折光检测器",
    instrument: "EasySep-3030 液相色谱系统",
    image: "/assets/cases/case-soy-oligosaccharides-cover.png",
    resultImage: "/assets/cases/case-soy-oligosaccharides-result.png",
    coverAlt: "大豆低聚糖HPLC-RID检测",
    standardReference: "农业农村部公告第628号-12-2022《转基因生物及其产品食用安全检测 大豆中寡糖含量的测定 液相色谱法》",
    background: "大豆低聚糖主要由蔗糖、棉子糖和水苏糖组成，其含量是评价大豆及相关制品质量的重要指标。",
    conditions: [["仪器系统", "EasySep-3030液相色谱系统"], ["检测器", "URI-3000 RID示差折光检测器"], ["检测组分", "蔗糖、棉子糖、水苏糖"], ["线性范围", "0.4–8 mg/mL"], ["重复性", "连续进样6针"]],
    result: "三种糖实现有效分离，在0.4–8 mg/mL范围内具有良好线性；连续6针重复性测试用于验证系统稳定性。",
    method: "按照官网所述参考方法，使用液相色谱与URI-3000 RID对三种大豆低聚糖进行分离、线性和重复性考察。",
    resultCaption: "蔗糖、棉子糖和水苏糖检测色谱图",
  },
  {
    id: "2eb1748f-4421-42d1-8c49-20b289c78b99",
    title: "URI-3000 RID 检测食品中五种糖",
    summary: "按照GB 5009.8—2023要求，检测果糖、葡萄糖、蔗糖、麦芽糖和乳糖。",
    industry: "食品与农产品",
    detector: "URI-3000 RID 示差折光检测器",
    instrument: "EasySep-3030 液相色谱系统",
    image: "/assets/cases/case-food-sugars-cover.png",
    resultImage: "/assets/cases/case-food-sugars-result.png",
    coverAlt: "食品中五种糖HPLC-RID检测",
    standardReference: "GB 5009.8—2023《食品安全国家标准 食品中果糖、葡萄糖、蔗糖、麦芽糖、乳糖的测定》",
    background: "果糖、葡萄糖、蔗糖、麦芽糖和乳糖是食品营养与质量控制中的常见检测组分，国家标准规定可采用HPLC-RI或HPLC-ELSD方法测定。",
    conditions: [["仪器", "EasySep-3030液相色谱系统，配备URI-3000 RID"], ["色谱柱", "NH2（4.6 mm × 250 mm，5 μm）"], ["流动相", "乙腈-水（75:25）"], ["流速", "1.0 mL/min"], ["柱温", "40 ℃"], ["检测池温度", "40 ℃"]],
    result: "五种糖实现有效分离，并在1–10 mg/mL国标浓度范围内表现出良好线性；连续6针用于重复性考察。",
    method: "采用氨基柱与URI-3000 RID，在国标规定的组分和浓度范围内开展分离、线性和重复性验证。",
    resultCaption: "食品中五种糖检测色谱图",
  },
  {
    id: "cae19f35-857e-4cdb-ad8c-a85d0088d10c",
    title: "HPLC-ELSD 检测安宫止血丸中盐酸水苏碱",
    summary: "按照《中国药典》2025年版要求，测定安宫止血丸中盐酸水苏碱含量。",
    industry: "中药与天然产物",
    detector: "UNIEX-8700 ELSD 蒸发光散射检测器",
    instrument: "EasySep-3030 液相色谱系统",
    image: "/assets/cases/case-angong-cover.png",
    resultImage: "/assets/cases/case-angong-result.png",
    coverAlt: "安宫止血丸盐酸水苏碱HPLC-ELSD检测",
    standardReference: "《中国药典》2025年版：安宫止血丸中盐酸水苏碱含量测定（HPLC-ELSD）",
    background: "盐酸水苏碱是安宫止血丸中益母草的目标待检成分，药典要求采用液相色谱-蒸发光散射检测法进行含量测定。",
    conditions: [["仪器系统", "EasySep-3030液相色谱系统"], ["检测器", "UNIEX-8700 ELSD"], ["色谱柱", "GS 120-5-Amide（250 × 4.6 mm，5 μm）"], ["测试对象", "盐酸水苏碱对照品与安宫止血丸供试品"]],
    result: "盐酸水苏碱对照品和供试品获得有效响应，重复性与系统适用性能够满足官网案例所述药典检测要求。",
    method: "对盐酸水苏碱对照品、供试品和连续进样重复性进行考察。",
    resultCaption: "盐酸水苏碱对照品色谱图",
  },
  {
    id: "c343150c-9c9a-4eb5-8c14-6248f74623a8",
    title: "毛细管凝胶电泳分析单克隆抗体纯度",
    summary: "使用AutoCE-3000对IgG1重组单抗开展还原与非还原CE-SDS纯度分析。",
    industry: "生物制药",
    detector: "UV/Vis 紫外可见检测器",
    instrument: "AutoCE-3000 全自动毛细管电泳系统",
    image: "/assets/cases/case-mab-cover.png",
    resultImage: "/assets/cases/case-mab-result.png",
    coverAlt: "单克隆抗体CE-SDS纯度分析",
    standardReference: "《中国药典》2025年版CE-SDS纯度分析要求；并参考USP、EP相关收载方法",
    background: "CE-SDS可用于评价单克隆抗体分子大小变异体。官网案例对IgG1样品的还原与非还原处理结果及重复性进行了验证。",
    conditions: [["仪器", "AutoCE-3000全自动毛细管电泳分离系统"], ["石英毛细管", "50 μm i.d.，有效长度26 cm"], ["分离电解质", "CE凝胶（蛋白专用）"], ["样品", "1 mg/mL IgG1"], ["分离条件", "-15 kV"], ["进样", "-8 kV，30 s/40 s"], ["检测波长", "220 nm"]],
    result: "还原单抗各组分迁移时间RSD不高于0.85%，校正峰面积百分比RSD不高于1.38%；非还原单抗主峰迁移时间RSD为0.36%，校正峰面积百分比RSD为0.06%。",
    method: "分别开展还原与非还原CE-SDS分析，并连续进样6次验证迁移时间和峰面积重复性。",
    resultCaption: "还原单抗CE-SDS纯度分析电泳图",
  },
  {
    id: "c68355d3-9dfe-4548-846f-b2db728b1af4",
    title: "HPLC-ELSD 检测泊洛沙姆188",
    summary: "采用EasySep-3030与UNIEX-8700 ELSD检测药用辅料泊洛沙姆188并考察线性。",
    industry: "化学药与药用辅料",
    detector: "UNIEX-8700 ELSD 蒸发光散射检测器",
    instrument: "EasySep-3030 液相色谱系统",
    image: "/assets/cases/case-poloxamer-cover.png",
    resultImage: "/assets/cases/case-poloxamer-result.png",
    coverAlt: "泊洛沙姆188 HPLC-ELSD检测",
    standardReference: "《中国药典》：泊洛沙姆188检测",
    background: "泊洛沙姆188是制剂中常用的增溶剂、稳定剂和乳化剂，准确测定含量是药用辅料质量控制的重要环节。",
    conditions: [["仪器", "EasySep-3030液相色谱系统"], ["检测器", "UNIEX-8700 ELSD"], ["色谱柱", "Poly RP-100（250 × 4.6 mm，5 μm）"], ["线性进样量", "1、2、5、10、15、30 μg"]],
    result: "峰面积与泊洛沙姆188进样质量的双对数线性方程为Y=1.9129X+1.6485，R²=0.9981。",
    method: "在多个进样质量水平下检测泊洛沙姆188，并以峰面积与进样质量双对数建立线性关系。",
    resultCaption: "泊洛沙姆188线性考察",
  },
  {
    id: "92fab9d2-d871-4786-bb80-0d01db4c53d0",
    title: "CE-SDS 分析10–200 kD蛋白Marker",
    summary: "使用CE-1000和市售CE凝胶分离10–200 kD范围内的14种蛋白Marker。",
    industry: "生物制药",
    detector: "UV/Vis 紫外可见检测器",
    instrument: "CE-1000 毛细管电泳系统",
    image: "/assets/cases/case-protein-marker-cover.png",
    resultImage: "/assets/cases/case-protein-marker-result.jpg",
    coverAlt: "蛋白Marker毛细管凝胶电泳分析",
    standardReference: "《中国药典》毛细管电泳法（通则0542）；并参考《欧洲药典》11.0相关方法",
    background: "CE-SDS可将传统SDS-PAGE蛋白分离转移到毛细管平台。官网案例使用市售NovoBio CE凝胶对Protein Ladder进行分析。",
    conditions: [["仪器", "CE-1000毛细管电泳系统"], ["检测器", "UV检测器"], ["柱温控制", "TriSep-3000毛细管液冷柱温箱"], ["分离介质", "NovoBio市售CE-SDS凝胶"], ["样品", "10–200 kD Protein Ladder，14种蛋白Marker"]],
    result: "10–200 kD范围内的14种蛋白标品得到有效分离，方法可用于蛋白、多肽和抗体的日常定性与定量分析。",
    method: "样品在SDS条件下变性并形成带负电复合物，随后按分子量在毛细管凝胶中分离并进行UV检测。",
    resultCaption: "10–200 kD蛋白Marker毛细管凝胶电泳图",
  },
  {
    id: "4b87d3e9-d853-403c-b9a5-07a8c3033779",
    title: "毛细管电泳分离PTA中的杂质",
    summary: "依据GB/T 30921.1—2014，使用AutoCE-3000分离精对苯二甲酸中的多种杂质。",
    industry: "化工与新材料",
    detector: "UV/Vis 紫外可见检测器",
    instrument: "AutoCE-3000 全自动毛细管电泳系统",
    image: "/assets/cases/case-pta-cover.png",
    resultImage: "/assets/cases/case-pta-result.png",
    coverAlt: "精对苯二甲酸杂质毛细管电泳分析",
    standardReference: "GB/T 30921.1—2014《工业用精对苯二甲酸（PTA）试验方法》",
    background: "PTA中的4-CBA和p-TOL等杂质会影响聚酯下游产品质量。国标收载的毛细管区带电泳法可对相关杂质进行定量分析。",
    conditions: [["仪器", "AutoCE-3000全自动毛细管电泳系统"], ["分离模式", "毛细管区带电泳（CZE）"], ["目标组分", "苯甲酸、4-CBA、p-TOL"], ["重复性", "连续进样6次"]],
    result: "PTA及三种杂质分离度均大于4.0；连续6针迁移时间RSD均在0.65%以内，峰面积RSD均在3%以内。",
    method: "使用AutoCE-3000对PTA样品中的苯甲酸、4-CBA和p-TOL进行分离并开展连续6针重复性测试。",
    resultCaption: "PTA及其杂质毛细管电泳分离图",
  },
  {
    id: "1957000e-5461-4edc-84e6-ef957dd2e122",
    title: "URI-3000 RID 检测食品中四种糖醇",
    summary: "按照GB 5009.279—2016要求，检测木糖醇、山梨醇、麦芽糖醇和赤藓糖醇。",
    industry: "食品与农产品",
    detector: "URI-3000 RID 示差折光检测器",
    instrument: "EasySep-3030 液相色谱系统",
    image: "/assets/cases/case-sugar-alcohols-cover.png",
    resultImage: "/assets/cases/case-sugar-alcohols-result.png",
    coverAlt: "食品中四种糖醇HPLC-RID检测",
    standardReference: "GB 5009.279—2016《食品安全国家标准 食品中木糖醇、山梨醇、麦芽糖醇和赤藓糖醇的测定》",
    background: "糖醇广泛用于无糖食品。国家标准规定可采用HPLC-RID或HPLC-ELSD检测木糖醇、山梨醇、麦芽糖醇和赤藓糖醇。",
    conditions: [["仪器", "EasySep-3030液相色谱系统，配备URI-3000 RID"], ["色谱柱", "NH2（4.6 mm × 250 mm，5 μm）"], ["流动相", "乙腈-水（70:30）"], ["流速", "1.0 mL/min"], ["柱温", "30 ℃"], ["检测池温度", "30 ℃"]],
    result: "四种糖醇实现有效分离，并在1.6–6.0 mg/mL国标浓度范围内表现出良好线性；连续6针用于重复性考察。",
    method: "使用氨基柱与URI-3000 RID对四种糖醇开展分离、线性和连续6针重复性验证。",
    resultCaption: "四种糖醇检测色谱图",
  },
  {
    id: "aa65fd29-fbbe-44da-afc0-cdd5504c05bf",
    title: "HPLC-ELSD 检测硫酸庆大霉素",
    summary: "按照《中国药典》2025年版要求，在强酸体系下检测硫酸庆大霉素C组分及有关物质。",
    industry: "化学药与药用辅料",
    detector: "UNIEX-8700 ELSD 蒸发光散射检测器",
    instrument: "EasySep-3030 液相色谱系统",
    image: "/assets/cases/case-gentamicin-cover.png",
    resultImage: "/assets/cases/case-gentamicin-result.png",
    coverAlt: "硫酸庆大霉素HPLC-ELSD检测",
    standardReference: "《中国药典》2025年版：庆大霉素C组分含量测定",
    background: "硫酸庆大霉素由多组分组成且缺少强紫外吸收基团。ELSD无需物质具有光学吸收特性，适合检测庆大霉素C组分。",
    conditions: [["仪器", "EasySep-3030液相色谱系统，配备UNIEX-8700 ELSD"], ["色谱柱", "C18（4.6 mm × 250 mm，5 μm）"], ["流动相", "0.2 mol/L三氟醋酸溶液-甲醇（96:4）"], ["流速", "0.8 mL/min"], ["柱温", "35 ℃"], ["ELSD参数", "载气2.8 L/min；蒸发/雾化温度110 ℃；增益4；不分流"]],
    result: "强酸体系下获得庆大霉素C组分检测响应，连续6针色谱图用于验证重复性，方案适合氨基糖苷类抗生素分析。",
    method: "按照官网列出的药典条件，使用C18柱和UNIEX-8700 ELSD检测庆大霉素C组分。",
    resultCaption: "庆大霉素C组分连续6针叠加色谱图",
  },
  {
    id: "73bf6f39-02ba-44de-9307-ac2483c31824",
    title: "毛细管凝胶电泳分析核酸样品",
    summary: "使用CE-1000分别分离人工合成小RNA与100–2000 bp DNA Marker。",
    industry: "生物制药",
    detector: "UV/Vis 紫外可见检测器",
    instrument: "CE-1000 毛细管电泳系统",
    image: "/assets/cases/case-nucleic-acid-cover.jpg",
    resultImage: "/assets/cases/case-nucleic-acid-result.jpg",
    coverAlt: "核酸样品毛细管凝胶电泳分析",
    standardReference: "部分实验参考《美国药典》mRNA疫苗质量控制分析方法",
    background: "核酸分子完整性分析对质量保证和工艺优化十分重要。毛细管凝胶电泳可按片段大小分离RNA与DNA，并减少传统凝胶染色操作。",
    conditions: [["仪器", "CE-1000毛细管电泳仪"], ["检测波长", "280 nm / 254 nm"], ["毛细管内径", "75 μm / 50 μm"], ["样品", "5种小核酸混合样；QDL 2,000 DNA Marker"], ["运行电压", "10 kV / 20 kV"], ["进样", "10 kV，10 s"], ["分离电解质", "RNA/DNA分析用CE凝胶"]],
    result: "5种3000–30000 Da小RNA片段及100–2000 bp QDL 2,000 DNA Marker均得到有效分离，满足日常片段分析需求。",
    method: "分别使用适配的小核酸和DNA分离凝胶，对人工合成RNA混合样与DNA Marker开展CGE-UV分析。",
    resultCaption: "QDL 2,000 DNA Marker毛细管凝胶电泳图",
  },
  {
    id: "5faf5a81-f654-4ee8-a577-c78b411e6ee2",
    title: "HPLC-ELSD 检测薏苡仁中甘油三油酸酯",
    summary: "按照《中国药典》要求，检测薏苡仁配方颗粒中的甘油三油酸酯。",
    industry: "中药与天然产物",
    detector: "UNIEX-8700 ELSD 蒸发光散射检测器",
    instrument: "EasySep-3030 液相色谱系统",
    image: "/assets/cases/case-coix-cover.jpg",
    resultImage: "/assets/cases/case-coix-result.jpg",
    coverAlt: "薏苡仁甘油三油酸酯HPLC-ELSD检测",
    standardReference: "《中国药典》：薏苡仁中甘油三油酸酯含量测定",
    background: "甘油三油酸酯是薏苡仁的主要药用活性成分之一，含量检测可用于原料和配方颗粒质量监控。",
    conditions: [["仪器", "EasySep-3030液相色谱系统，配备UNIEX-8700 ELSD"], ["色谱柱", "Bischoff Prontosil Kromaplus C18（250 × 4.6 mm，5 μm）"], ["流动相", "乙腈-二氯甲烷（65:35），等度洗脱"], ["流速", "1.2 mL/min"], ["柱温", "25 ℃"]],
    result: "甘油三油酸酯对照品与薏苡仁配方颗粒均获得有效响应，方法准确、灵敏，可满足日常分析检测要求。",
    method: "采用等度洗脱，对甘油三油酸酯对照品、重复性和薏苡仁配方颗粒样品进行检测。",
    resultCaption: "甘油三油酸酯对照品典型色谱图",
  },
  {
    id: "8c7f3edb-a12c-45fd-84fd-88ddca500ecf",
    title: "HPLC-ELSD 检测酸枣仁皂苷A",
    summary: "针对皂苷类弱紫外吸收特性，按照《中国药典》2020年版要求检测酸枣仁皂苷A。",
    industry: "中药与天然产物",
    detector: "UNIEX-8700 ELSD 蒸发光散射检测器",
    instrument: "通微 HPLC 液相色谱系统",
    image: "/assets/cases/case-jujuboside-cover.jpg",
    resultImage: "/assets/cases/case-jujuboside-result.jpg",
    coverAlt: "酸枣仁皂苷A HPLC-ELSD检测",
    standardReference: "《中国药典》2020年版：酸枣仁皂苷A含量测定",
    background: "酸枣仁皂苷A是酸枣仁的活性与质量控制成分，三萜皂苷紫外吸收弱，ELSD可避免UV检测响应不足的问题。",
    conditions: [["仪器", "通微液相色谱系统，配备UNIEX-8700 ELSD"], ["色谱柱", "Bischoff Prontosil Kromaplus C18（250 × 4.6 mm，5 μm）"], ["洗脱方式", "梯度洗脱"], ["梯度程序", "0–15 min A 20→40%；15–28 min A 40%；28–30 min A 40→70%；30–32 min A 70→100%"]],
    result: "酸枣仁皂苷A对照品和供试品均获得有效分离响应，可用于酸枣仁中指标成分含量检测。",
    method: "采用C18色谱柱和梯度洗脱，对酸枣仁皂苷A对照品及供试品进行HPLC-ELSD检测。",
    resultCaption: "酸枣仁皂苷A对照品色谱图",
  },
  {
    id: "b87fc3f2-8bcb-49ba-a498-8f060f97bcc9",
    title: "HPLC-ELSD 测定电子烟烟液中四种甜味剂",
    summary: "同时检测电子烟烟液中的安赛蜜、甜蜜素、三氯蔗糖和阿斯巴甜。",
    industry: "烟草制品",
    detector: "ELSD 蒸发光散射检测器",
    instrument: "通微 HPLC 液相色谱系统",
    image: "/assets/cases/case-ecig-sweeteners-cover.jpg",
    resultImage: "/assets/cases/case-ecig-sweeteners-result.jpg",
    coverAlt: "电子烟烟液四种甜味剂HPLC-ELSD检测",
    standardReference: "",
    background: "甜味剂用于调节电子烟风味，超限量或超范围使用会带来质量风险。官网案例建立四种常见甜味剂的HPLC-ELSD检测方法。",
    conditions: [["仪器", "通微液相色谱系统，配备ELSD"], ["色谱柱", "GlobalSIL C18-ST（250 × 4.6 mm，5 μm）"], ["检测组分", "安赛蜜、甜蜜素、三氯蔗糖、阿斯巴甜"], ["标准溶液", "12.5、25、50、75、100 μg/mL"]],
    result: "四种甜味剂连续6针保留时间RSD为0.02%–0.12%，峰面积RSD为1.23%–3.11%，并建立了双对数标准曲线。",
    method: "对四种甜味剂混合标准品开展分离、连续6针重复性和五水平线性考察。",
    resultCaption: "电子烟烟液四种甜味剂对照品色谱图",
  },
  {
    id: "f13481b3-f0d6-48cc-80b9-6ee492b3cb16",
    title: "HPLC-ELSD 测定壳聚糖含量",
    summary: "按照GB/T 38479—2021要求，通过壳聚糖水解产物氨基葡萄糖盐酸盐测定壳聚糖含量。",
    industry: "化工与新材料",
    detector: "ELSD 蒸发光散射检测器",
    instrument: "通微 HPLC 液相色谱系统",
    image: "/assets/cases/case-chitosan-cover.jpg",
    resultImage: "/assets/cases/case-chitosan-result.jpg",
    coverAlt: "壳聚糖含量HPLC-ELSD检测",
    standardReference: "GB/T 38479—2021《壳聚糖含量测定 高效液相色谱法》",
    background: "壳聚糖用于水处理、医疗、食品和保健食品等领域。官网案例按照国家标准采用HPLC-ELSD测定其水解产物。",
    conditions: [["仪器", "通微液相色谱系统，配备ELSD"], ["色谱柱", "Shodex Asahipak NH2P-50 4E（250 × 4.6 mm，5 μm）"], ["检测对象", "壳聚糖水解产物氨基葡萄糖盐酸盐"], ["标准溶液", "1.0、1.5、2.0、2.5、3.0、3.5 mg/mL"]],
    result: "氨基葡萄糖盐酸盐获得有效分离响应，重复性和线性测试表明该方法可满足壳聚糖含量日常检测需求。",
    method: "以氨基葡萄糖盐酸盐为检测对象，对照品、重复性和六水平线性进行考察。",
    resultCaption: "氨基葡萄糖盐酸盐重复性色谱图",
  },
  {
    id: "1ece482b-631d-4112-8e13-4459d2ce57b4",
    title: "HPLC-ELSD 分离检测黄芪甲苷",
    summary: "按照《中国药典》要求，使用HPLC-ELSD检测黄芪中黄芪甲苷含量。",
    industry: "中药与天然产物",
    detector: "ELSD 蒸发光散射检测器",
    instrument: "通微 HPLC 液相色谱系统",
    image: "/assets/cases/case-astragaloside-cover.jpg",
    resultImage: "/assets/cases/case-astragaloside-result.jpg",
    coverAlt: "黄芪甲苷HPLC-ELSD检测",
    standardReference: "《中国药典》：黄芪中黄芪甲苷含量测定",
    background: "黄芪甲苷是黄芪的主要活性与质量控制成分，约201 nm处只有较弱末端吸收，ELSD可改善常规UV基线噪声和重现性问题。",
    conditions: [["仪器", "通微液相色谱系统，配备ELSD"], ["色谱柱", "Bischoff Prontosil Kromaplus C18（250 × 4.6 mm，5 μm）"], ["测试对象", "黄芪甲苷对照品与黄芪供试品"], ["重复性", "对照品连续进样考察"]],
    result: "黄芪甲苷对照品和黄芪供试品均获得有效分离，可用于中药材中指标成分的含量检测。",
    method: "使用C18色谱柱和ELSD，对重复性、黄芪甲苷对照品及黄芪供试品进行检测。",
    resultCaption: "黄芪甲苷对照品典型色谱图",
  },
  {
    id: "6e074ca0-13f5-4f6d-83f3-319259410cd0",
    title: "固相萃取-毛细管电泳检测环境中头孢类抗生素",
    summary: "结合SPE富集与CE-UV分离，检测环境水样中的十种头孢类抗生素。",
    industry: "环境检测",
    detector: "UV/Vis 紫外可见检测器",
    instrument: "CE-1000 毛细管电泳系统",
    image: "/assets/cases/case-cephalosporins-cover.png",
    resultImage: "/assets/cases/case-cephalosporins-result.png",
    coverAlt: "环境水样头孢类抗生素毛细管电泳检测",
    standardReference: "",
    background: "固相萃取可用于环境水样中抗生素的纯化与浓缩，毛细管电泳则提供快速、高效和低试剂消耗的分离检测。",
    conditions: [["仪器", "CE-1000毛细管电泳系统，配备UV/Vis检测器"], ["SPE富集", "Oasis PriME HLB柱；pH 2.5；纯甲醇6 mL"], ["石英毛细管", "50 μm i.d.，45 cm有效长度，总长60 cm"], ["缓冲液", "40 mmol/L磷酸盐"], ["运行电压", "15 kV"], ["进样", "80 mbar × 10 s"], ["检测波长", "195 nm"]],
    result: "十种头孢类抗生素在5.0 μg/mL水平得到有效分离；对自来水、地表水和工业废水的测试表明SPE-CE可提供环境污染检测参考。",
    method: "先使用SPE对500 mL水样进行纯化和浓缩，再用CE-UV分离头孢克肟、头孢氨苄等十种抗生素。",
    resultCaption: "十种头孢类抗生素毛细管电泳分离图",
  },
];

export const officialCases = cases.map(({ conditions, method, resultCaption, ...item }, index) => {
  const officialResult = officialResults[index];
  return {
    ...item,
    resultImage: officialResult?.figures?.[0]?.src || item.resultImage,
    conditionRows: makeConditions(conditions),
    contentHtml: makeArticle({ ...item, method, resultCaption }, officialResult),
    contact,
  };
});
